#!/usr/bin/env node
/**
 * Writes the map a crawler follows: `public/sitemap.xml`.
 *
 * The three top-level routes and one address per hull, the hulls read from the
 * installed package rather than listed here. A hand-written list of hull
 * symbols would be the private copy of package data constitution II forbids: it
 * would keep working, and would stop tracking the package at the next pin move.
 * That is the follow-up `design/search-visibility.md` recorded as the highest
 * value one, and this is it.
 *
 * The file stays committed rather than generated into the build. A pin move
 * that adds a hull then shows up in review as an added address, which is the
 * one place anybody would notice a hull arriving or leaving; a file rebuilt
 * into `dist` would be correct and unread. `--check` refuses a committed file
 * that no longer matches the installed package, so the two cannot drift.
 *
 *   node scripts/generate-sitemap.mjs
 *   node scripts/generate-sitemap.mjs --check
 *
 * Everything else follows from this file. The deployment publishes one document
 * per address it advertises, so a hull listed here is a hull that answers.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { declaredOrigin, publishedAddresses } from './search/published-addresses.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

/** The file that declares where this application is published. */
export const ORIGIN_SOURCE = 'src/app/platform/browser/site-address.ts';

/** The map itself. */
export const SITEMAP = 'public/sitemap.xml';

/**
 * The header the file carries.
 *
 * No text here may contain two hyphens together. Both readers of this file cut
 * comments in a single pass and then refuse whatever still opens or closes one,
 * and a comment body holding `-` `-` is not cut at all — so a sitemap that
 * explained itself with a command-line flag in it would fail the deployment it
 * was explaining.
 */
const HEADER = `<!--
  Generated by \`pnpm run search:sitemap\`. Do not edit this file by hand.

  One address per top level route, then one per hull, the hulls read from the
  installed Almanac. Run the generator after a package pin move; the policy
  checker refuses a file that no longer matches the package it was built from.

  This is also the list the deployment publishes as real addresses. GitHub Pages
  would otherwise serve each of these from \`404.html\`, and a crawler drops a 404
  whatever the body says, so \`scripts/publish-static-routes.mjs\` writes one
  document per address below, each carrying that address's own canonical link,
  title, description and card. Adding an address here publishes it; there is no
  second list to keep in step.

  Neither \`changefreq\` nor \`priority\` is stated: Google has ignored both for
  years, and a file that states things nobody reads invites belief in them.
  \`lastmod\` is absent for a reason of its own, recorded in
  specs/011-interface-foundations/design/search-visibility.md.
-->`;

/** The sitemap as text, given the addresses it lists. */
export function sitemapDocument(addresses) {
  const entries = addresses
    .map((entry) => `  <url>\n    <loc>${entry.address}</loc>\n  </url>`)
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
${HEADER}
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
`;
}

async function main() {
  const origin = declaredOrigin(await readFile(join(ROOT, ORIGIN_SOURCE), 'utf8'));
  const document = sitemapDocument(publishedAddresses({ origin }));
  const path = join(ROOT, SITEMAP);

  if (process.argv.includes('--check')) {
    const committed = await readFile(path, 'utf8').catch(() => null);
    if (committed === document) {
      return;
    }
    console.error(
      committed === null
        ? `${SITEMAP} is missing. Run \`pnpm run search:sitemap\`.`
        : `${SITEMAP} does not match the installed package. Run \`pnpm run search:sitemap\` and commit the result.`,
    );
    process.exitCode = 1;
    return;
  }

  await writeFile(path, document, 'utf8');
  console.log(`${SITEMAP}: ${publishedAddresses({ origin }).length} addresses`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await main();
}
