import { inject } from '@angular/core';
import type { Provider } from '@angular/core';
import { ActiveBuildStore } from '../active-build/active-build.store';
import { SLEF_FALLBACK, type SlefFallback } from '../build-link/slef-fallback.port';
import { SlefStore } from './slef.store';

/**
 * Feature 004's answer to feature 001's one question: "can this build leave?"
 *
 * The seam exists because two different moments ask it — the workspace's own
 * Export action, and a link refusal reaching for the other way out — and
 * neither should have to know how a payload is produced. Both open the same
 * layer, and the layer opens on the SLEF format when the link is the thing that
 * just failed.
 *
 * It reaches only the two signal stores on purpose. Opening a layer must not
 * drag the Almanac, the serializer and the delivery ports into the shell's own
 * bundle: the layer is deferred, and the payload is generated by the layer once
 * it is on screen — which, since the layer opens on the payload as canvas 1c
 * draws it, is every time it opens rather than only when a Commander asks for
 * SLEF. That is work inside a chunk that has already been fetched, not work at
 * startup; asking a coordinator here instead would load every one of those at
 * startup, for a control most sessions never press.
 *
 * `export()` returns false rather than opening an empty layer when there is no
 * active build: a layer that says nothing about nothing is worse than a control
 * that was honestly unavailable.
 */
function slefFallback(): SlefFallback {
  const store = inject(SlefStore);
  const active = inject(ActiveBuildStore);

  return {
    get available(): boolean {
      return active.loadout() !== null;
    },
    export(): boolean {
      if (active.loadout() === null) {
        return false;
      }
      // The format is chosen by which of the two moments this was: a link that
      // has just been refused is the reason the other way out is being reached
      // for, so the layer opens on it whatever was last chosen. An ordinary
      // Export opens on whatever the store holds, which starts where canvas 1c
      // draws the list starting — on the payload.
      if (active.link().kind === 'refused') {
        store.selectExportMode('slef');
      }
      store.openLayer('export');
      return true;
    },
  };
}

/** Replaces the "not available yet" default with the delivered capability. */
export const SLEF_FALLBACK_PROVIDER: Provider = {
  provide: SLEF_FALLBACK,
  useFactory: slefFallback,
};
